source "https://github.com/CocoaPods/Specs.git"

project 'iOSExample.xcodeproj/'
platform :ios, '10.0'

target 'iOSExample' do
    
    use_frameworks!
    
    # Pods for iOSExample
    pod 'ExtSwift', :path => '../../'
    
    target 'iOSExampleTests' do
        # Pods for testing
    end
    
end
